### ISSUE TITLE
URL.js Version Bump

### ISSUE THREAD

**Issue by breannawhipple-wk** [duzun/URL.js#5]
Hello - we are in need of a version bump in order to resolve an internal CVE.  Are there any plans to update URL.js?

Thank you!

**Comment by duzun** [comment]
Hello @breannawhipple-wk 
I don't have any short term plans, but long term I intend to convert the code to ESM or even TS.
Do you have any ideas for improvements?

**Comment by duzun** [comment]
@breannawhipple-wk done, increased the version to `v0.2.6` - the last version of v0.
