### ISSUE TITLE
How to write ts declaration file

### ISSUE THREAD

**Issue by GuiYuanLu** [duzun/URL.js#6]
I want to use 'url-js' in my React+TypeScript project, but I get an error that the declaration file for module 'url-js' cannot be found. "/Users/admin/Desktop/react_demo_project/ee-openapi-h5/node_modules/url-js/dist/url.js" implicitly has type "any".
   Try using `npm i --save-dev @types/url-js` (if it exists), or add a new declaration (.d.ts) file containing `declare module 'url-js';` ts(7016) .

So how to write the declaration file of ts?

**Comment by duzun** [comment]
I have to create the definitions file and add it to the repo.

**Comment by duzun** [comment]
I have added .d.ts files for v2.0.0.

Please, let me know if it works for you.

Thanks.

**Comment by duzun** [comment]
Here is my attempts at `.d.ts` [294dbb64](https://github.com/duzun/URL.js/commit/294dbb64680d67b0952bd3099a16c4ed05564d86)
